project:
  type: website
  preview:
    browser: true

website:
  # Name of site in navbar
  title: "Reproducing Allen et al. 2020"
  # Favicon image for site
  favicon: "quarto_site/stars_logo_blue.png"
  # Adds edit and issue buttons to footer
  repo-url: https://github.com/pythonhealthdatascience/stars-reproduce-allen-2020
  repo-actions: [edit, issue]
  # Settings for navbar across top of page
  navbar:
    logo: "quarto_site/stars_logo_blue.png"
    # Left-aligned within navbar...
    left:
      - text: Original study
        menu:
          - quarto_site/study_publication.qmd
          - quarto_site/study_code.qmd
      - text: Reproduction code
        menu:
          - reproduction/example.ipynb
      - text: Evaluation
        menu:
          - evaluation/scope.qmd
          - evaluation/reproduction_success.qmd
          - evaluation/artefacts.qmd
          - evaluation/badges.qmd
          - evaluation/reporting.qmd
      - evaluation/logbook.qmd
      - text: Report
        href: evaluation/reproduction_report.qmd
    # Right-aligned within navbar...
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-allen-2020
  page-footer:
    left: |
      [![](https://raw.githubusercontent.com/pythonhealthdatascience/stars-logo/main/stars_logo_blue_text.png){fig-alt="STARS" width=300px}](https://github.com/pythonhealthdatascience)
    center:
      - text: "Changelog"
        href: CHANGELOG.md
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-allen-2020

format:
  html:
    theme:
      light: cosmo
      dark: [solar, quarto_site/dark.scss]
    toc: true