project:
  type: website
  preview:
    browser: true

website:
  # Name of site in navbar
  title: "Reproducing Monks et al. 2016"
  # Favicon image for site
  favicon: "docs/stars_logo_blue.png"
  # Settings for navbar across top of page
  navbar:
    logo: "docs/stars_logo_blue.png"
    # Left-aligned within navbar...
    left:
      - text: Code
        menu:
          - simulation/example.ipynb
      - docs/blog_index.qmd
      - text: Guidelines
        menu:
          - href: docs/badges.qmd
    # Right-aligned within navbar...
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-monks-2016
  page-footer:
    left: |
      [![](https://raw.githubusercontent.com/pythonhealthdatascience/stars-logo/main/stars_pointy_v2_text.png){fig-alt="STARS" width=300px}](https://github.com/pythonhealthdatascience)
    center: |
      This work forms part of work package 1 on the STARS project.
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-monks-2016

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true