project:
  type: website
  preview:
    browser: true

website:
  # Name of site in navbar
  title: "Reproducing Monks et al. 2016"
  # Favicon image for site
  favicon: "quarto_site/stars_logo_blue.png"
  # Settings for navbar across top of page
  navbar:
    logo: "quarto_site/stars_logo_blue.png"
    # Left-aligned within navbar...
    left:
      - text: Original study
        menu:
          - quarto_site/study_summary.qmd
          - quarto_site/study_publication.qmd
          - quarto_site/study_code.qmd
      - text: Reproduction code
        menu:
          - reproduction/scripts/example.ipynb
      - text: Evaluation
        menu:
          - evaluation/reproduction_success.qmd
          - evaluation/artefacts.qmd
          - evaluation/badges.qmd
          - evaluation/reporting.qmd
      - evaluation/logbook.qmd
      - text: Report
        href: evaluation/reproduction_report.qmd
    # Right-aligned within navbar...
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-monks-2016
  page-footer:
    left: |
      [![](https://raw.githubusercontent.com/pythonhealthdatascience/stars-logo/main/stars_logo_blue_text.png){fig-alt="STARS" width=300px}](https://github.com/pythonhealthdatascience)
    center: |
      This work forms part of work package 1 on the STARS project.
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-monks-2016

format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true