name: covid19
channels:
  - defaults
dependencies:
  - joblib=0.14.1
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - pytest=5.3.5
  - python=3.8.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - statsmodels=0.11.0
  - pip:
    - simpy==3.0.11

